services:
  app:
    image: registry.flarewebs.com/fiifidev/api_base
    restart: always
    ports:
      - "8000:80"
    env_file:
      - .env
    networks:
      - db-network


networks:
  db-network:
    external: true
    name: 'db-network'