services:
  app:
    image: registry.flarewebs.com/fiifidev/api_base
    restart: always
    ports:
      - "8000:80"
    env_file:
      - .env.dev
    networks:
      - postgres-network


networks:
  postgres-network:
    external: true
    name: 'postgres-network'