services:
  app:
    image: registry.flarewebs.com/fiifidev/blog_test
    restart: always
    ports:
      - "${APP_PORT}:80"
    env_file:
      - .env
    networks:
      - db-network

networks:
  db-network:
    external: true
    name: 'db-network'