"""add store field

Revision ID: 4eed39e3e6d4
Revises: 9e651047efb2
Create Date: 2023-03-12 16:25:05.566182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eed39e3e6d4'
down_revision = '9e651047efb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('created_at', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'created_at')
    # ### end Alembic commands ###
